services:
  mysql-service:
    image: mysql/mysql-server:8.0.32-1.2.11-server
    command: --default-authentication-plugin=mysql_native_password
    container_name: 'mysql-server'
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - ./log/mysql:/var/log/mysql:rw
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=eventos_ti
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    expose:
      - '3306'
  
  eventos-ti:
    image: rodrigoamora/rodrigo-springboot:latest
    container_name: 'eventos-ti'
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service

networks:
  spring-boot-mysql-network:
    driver: bridge

volumes:
  mysql-data: