services:
  mysql-service:
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    container_name: 'mysql-service'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - spring-boot-mysql-network
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=eventos_ti
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  
  eventos-ti:
    image: rodrigoamora/rodrigo-springboot:latest
    container_name: 'eventos-ti'
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service

networks:
  spring-boot-mysql-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local