apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-app
  template:
    metadata:
      labels:
        app: tech-app
    spec:
      containers:
        - name: tech-app
          image: rodrigoamora/rodrigo-springboot
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secrets
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: MYSQL_URL
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: MYSQL_HOST
            - name: MySQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MySQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: MYSQL_DATABASE
          resources:
            requests:
              cpu: "100m"