name: Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubunut-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Package
      run: nvm package
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      package: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
	  java-version: '17'
          distribution: 'adopt'
          package: '*.jar'
      - name: Publish package
        run: mvn --batch-mode- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
